//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_AT_Command
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendMessage
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_Send { get; set; }
        public string Name_Contact { get; set; }
        public string Number_Contact { get; set; }
        public string Message { get; set; }
    }
}
